name: Remote Update Projects
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Setup env
        run: |
          echo "project-folder=\client" >> $GITHUB_ENV
          echo "solution-name=client" >> $GITHUB_ENV
          echo "project-key=esg-ssimpson_sonarcloud-unity-action" >> $GITHUB_ENV
          echo "organization=esg-ssimpson" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          token: ${{ secrets.SUBMODULE_PULL }}
          submodules: 'true'
      - name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@v1
        with:
          project-path: ${{ github.workspace }}${{ env.project-folder }}
      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
      - name: Generate solution and project files
        shell: cmd
        run: |
          "${{ env.UNITY_PATH }}" -batchmode -nographics -logFile - -executeMethod UnityEditor.SyncVS.SyncSolution -projectPath ${{ github.workspace }}${{ env.project-folder }} -quit
      - name: Update project files
        shell: cmd
        run: |
          "${{ env.UNITY_PATH }}" -batchmode -nographics -logFile - -executeMethod EastSideGames.ThirdParty.SonarCloud.UpdateProjects.Update -projectPath ${{ github.workspace }}${{ env.project-folder }} -quit
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .${{ env.project-folder }}\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\client\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .${{ env.project-folder }}\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          cd .${{ env.project-folder }}
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ env.project-key }}" /o:"${{ env.organization }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          msbuild /target:Rebuild ${{ env.solution-name }}.sln 
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"